var FilterConstants = {
  FILTERS_RECEIVED: "FILTERS_RECEIVED",
  BOUND_FILTER_RECEIVED: "BOUND_FILTER_RECEIVED",
  SEATING_FILTER_RECEIVED: "SEATING_FILTER_RECEIVED"
};

module.exports = FilterConstants;
